# Site settings
title: nipy.org
description: "nipy.org"
url: "nipy.org"
author:
  name: "nipy"
  email: "neuroimaging@python.org"
  url: "nipy.github.io"

# Build settings
baseurl: "/"
markdown: kramdown
source: .
destination: ./_site
permalink: "/:title"
paginate: 8
paginate_path: /page:num/

# Custom variables
version: "1.1.0"
googleanalytics: "UA-69411900-1"

# Options
reverse: true

